import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'

const title = 'LightCraft vs Lightroom - Does This Free Photo Editor Actually Work?'
const description = 'My hands-on LightCraft vs Lightroom comparison with real photos. See differences in speed, presets, subject masking, RAW rendering, and JPEG exports.'
const url = 'https://www.chrisbrenzel.com/photography/lightcraft-vs-lightroom'
const base = '/images/lightcraft-vs-lightroom/'
export const metadata: Metadata = {
  title, description, alternates: { canonical: url },
  openGraph: { title, description, url, type: 'article', publishedTime: '2026-10-08', authors: ['Christopher Brenzel'], images: [{ url: base + 'balloon-lightcraft-adjusted.jpg', width: 1502, height: 1883, alt: 'Colorful hot-air balloons edited in LightCraft' }] },
  twitter: { card: 'summary_large_image', title, description, images: [base + 'balloon-lightcraft-adjusted.jpg'] },
}

function Photos({ items, caption }: { items: { file: string, label: string, alt: string, width: number, height: number }[], caption: string }) {
  return <figure className="my-8"><div className={`grid gap-5 ${items.length === 3 ? 'md:grid-cols-3' : 'md:grid-cols-2'}`}>
    {items.map(item => <div key={item.file}><p className="mb-2 text-sm font-semibold text-[#f5f0eb]">{item.label}</p><a href={base + item.file} target="_blank" rel="noopener noreferrer" aria-label={`Open larger image, ${item.label}`}><Image src={base + item.file} alt={item.alt} width={item.width} height={item.height} sizes="(max-width: 768px) 100vw, 480px" className="h-auto w-full rounded" /></a></div>)}
  </div><figcaption className="mt-3 text-sm text-white/60">{caption} Select an image to view it larger.</figcaption></figure>
}
const photo = (file: string, label: string, alt: string, width: number, height: number) => ({ file, label, alt, width, height })
const sections = [
  ['test', 'How I compared the editors'], ['speed', 'Speed and stability'], ['newborn', 'Newborn photo'], ['shed', 'Minimal shed edit'], ['presets', 'Presets and balloon photo'], ['masking', 'Subject masking'], ['raw', 'Butterfly RAW rendering'], ['exports', 'JPEG export sizes'], ['workflow', 'AI, cloud, and learning curve'], ['verdict', 'My verdict'], ['faq', 'Frequently asked questions'],
]
const faqs = [
  ['Does LightCraft actually work as a photo editor?', 'Yes. I used it to edit and export the photos shown here. It handled basic adjustments and produced usable results, although masking and the default rendering of one RAW file showed clear limitations.'],
  ['Is LightCraft a free Lightroom alternative?', 'LightCraft is offered as a free, open-source photo editor. For my basic editing needs it is a credible alternative, but this test did not establish complete feature parity with Lightroom.'],
  ['Is LightCraft faster than Lightroom?', 'It felt much more responsive on my computer. However, my newborn edits each took about 15 minutes, for different reasons. I have not measured a speed advantage across every task or computer.'],
  ['Can you import Lightroom presets into LightCraft?', 'I applied the same preset in both editors, but the results looked noticeably different. I manually adjusted the LightCraft balloon edit to get closer to Lightroom. Preset import and matching appearance are separate questions.'],
  ['Is LightCraft subject masking as good as Lightroom?', 'In my turkey vulture test, no. LightCraft included a broad area of sky, while Lightroom followed the bird, pole, and attached hardware much more precisely.'],
  ['Can LightCraft replace Lightroom for RAW editing?', 'It may cover straightforward edits, but I would test your own RAW files before switching. My butterfly photo showed a purple haze in the LightCraft preview before editing, and that haze remained in the exported JPEG.'],
]
const article = { '@context': 'https://schema.org', '@type': 'BlogPosting', headline: title, description, datePublished: '2026-10-08', dateModified: '2026-10-08', author: { '@type': 'Person', name: 'Christopher Brenzel', url: 'https://www.chrisbrenzel.com' }, mainEntityOfPage: url, image: 'https://www.chrisbrenzel.com' + base + 'balloon-lightcraft-adjusted.jpg' }

export default function LightCraftComparison() {
  return <main className="pt-14"><article className="mx-auto max-w-5xl px-6 py-20 md:py-28">
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(article) }} />
    <Link href="/photography/field-notes" className="text-sm text-[#6fcf97] hover:underline">Back to Field Notes</Link>
    <header className="mt-8 mb-10"><p className="text-sm text-white/60">Photography Editing · October 8, 2026 · Christopher Brenzel</p><h1 className="mt-4 font-serif text-4xl md:text-5xl leading-tight text-[#f5f0eb]">{title}</h1><p className="mt-6 text-xl leading-relaxed text-white/75">A free editor that feels familiar, with real tradeoffs in presets, masking, and RAW rendering.</p></header>
    <div className="space-y-6 text-base leading-relaxed text-white/75 [&_h2]:text-2xl [&_h2]:font-serif [&_h2]:text-[#f5f0eb] [&_h2]:pt-8 [&_h3]:text-lg [&_h3]:font-semibold [&_h3]:text-[#f5f0eb] [&_a]:underline [&_a]:underline-offset-4 [&_section]:scroll-mt-24">
      <p>I wanted to edit photos without constantly pushing my computer to its limits. Adobe Creative Cloud has been frustrating on my machine, with slowdowns, freezing, and crashes interrupting my workflow. LightCraft caught my attention because it is free and looks familiar to someone coming from Lightroom.</p>
      <p>Is it too good to be true? In my experience, no. It works as a photo editor, and I could get close to my Lightroom results on several photos. But the comparison also revealed limitations that matter, especially automatic subject masking and the starting appearance of one RAW file.</p>
      <p><strong>My early verdict</strong> - LightCraft feels much faster and handles basic editing well. Lightroom still gives me a stronger starting point for precise masks, and moving presets between editors requires more care than I expected.</p>
      <nav aria-label="Article contents" className="rounded border border-white/15 p-6"><p className="font-semibold text-[#f5f0eb] mb-3">In this comparison</p><ul className="grid gap-2 md:grid-cols-2">{sections.map(([id, label]) => <li key={id}><a href={'#' + id}>{label}</a></li>)}</ul></nav>
      <section id="test"><h2>How I compared LightCraft and Lightroom</h2><p className="mt-4">I used five photographs covering a newborn portrait, an old shed, colorful hot-air balloons, a turkey vulture, and a butterfly on a thistle. These are practical examples from my own editing workflow, rather than a controlled benchmark.</p><p className="mt-4">Some tests involved minimal editing. Others compared the same preset or checked subject selection. For the balloons, I also manually adjusted the LightCraft result to get closer to Lightroom. For the butterfly, I compared previews before editing and exported both preset-applied images as JPEGs at 100% quality.</p><p className="mt-4">The results reflect my computer and the software I used in October 2026. I did not record the exact app versions or system specifications, so these observations should not be read as universal performance claims.</p></section>
      <section id="speed"><h2>Speed and stability - Why I tried a free Adobe Lightroom alternative</h2><p className="mt-4">LightCraft feels much more responsive on my computer. Lightroom and the broader Creative Cloud setup have repeatedly brought me up against my computer&apos;s processing limits, with freezing and crashes becoming a source of frustration.</p><p className="mt-4">That does not mean every LightCraft edit took less time. The newborn photo took about 15 minutes in each program. In LightCraft, I was learning the interface. In Lightroom, the application was slow and would not import the LightCraft preset I tried, so I recreated the adjustments manually.</p><p className="mt-4">Those are different kinds of friction. I can get more familiar with an interface, but waiting for an application remains frustrating even when I know exactly what I want to do.</p></section>
      <section id="newborn"><h2>Newborn photo - Different color, similar editing time</h2><p className="mt-4">The newborn comparison produced two usable but different-looking edits. The LightCraft export is brighter and pinker. The comparison export is warmer, with deeper shadows. These differences reflect the finished adjustments, and do not by themselves prove that one editor handles skin tones better.</p>
      <Photos items={[photo('newborn-lightcraft.jpg','LightCraft','Newborn feet and lavender wrap edited in LightCraft',4977,6317),photo('newborn-reference.jpg','Comparison export','Warmer comparison edit of newborn feet and lavender wrap',4979,6224)]} caption="Both edits took about 15 minutes. The second file was supplied as DSC07916.jpg, without a separately confirmed editor label." />
      <p>The feet and blanket are the useful areas for comparing texture. The face is outside the plane of focus in both images.</p></section>
      <section id="shed"><h2>Minimal editing - The shed photos look nearly the same</h2><p className="mt-4">I kept the shed edit minimal, and the two results look very close at normal viewing size. There are small differences in framing and color, but I do not see an obvious visual advantage in either finished image.</p>
      <Photos items={[photo('shed-reference.jpg','Comparison export','Weathered wooden shed surrounded by greenery',4923,5785),photo('shed-lightcraft.jpg','LightCraft','Minimal LightCraft edit of an old wooden shed',4825,5756)]} caption="A straightforward edit produced closely comparable results. The first file was supplied as DSC09482.jpg." />
      <p>This is a useful answer to the basic question of whether LightCraft actually works. For this simple edit, it gave me a result I was happy with.</p></section>
      <section id="presets"><h2>Do Lightroom presets look the same in LightCraft?</h2><p className="mt-4">Not in my balloon test. Applying the same preset produced a much darker, more muted starting result in LightCraft. Lightroom&apos;s yellow balloon was brighter, and the sky was lighter.</p><p className="mt-4">I then adjusted LightCraft manually to match the Lightroom photo and got very close overall. The revised LightCraft version has deeper blacks and more pronounced contrast, but it shows that I could move toward the look I wanted.</p>
      <Photos items={[photo('balloon-lightcraft-preset.jpg','LightCraft with preset','Darker LightCraft balloon photo after applying the preset',1502,1883),photo('balloon-lightroom.jpg','Lightroom with same preset','Brighter Lightroom balloon photo with the same preset',1511,1889),photo('balloon-lightcraft-adjusted.jpg','LightCraft after adjustments','LightCraft balloon edit manually adjusted toward Lightroom',1502,1883)]} caption="Preset compatibility did not mean identical appearance in this test." />
      <p>The <a href="https://github.com/storytold/lightcraft">LightCraft project documentation</a> lists XMP preset support. My experience adds a practical qualification. Importing a preset and reproducing its Lightroom appearance are separate questions.</p><p className="mt-4">There are plenty of free presets in the Lightroom ecosystem, which can be useful or overwhelming. If you already rely on a small set, test those specific presets in LightCraft. Also, Lightroom preset import into LightCraft does not establish that Lightroom can import a LightCraft preset. My reverse import attempt on the newborn edit did not work.</p></section>
      <section id="masking"><h2>Subject masking - The biggest limitation I found</h2><p className="mt-4">I deliberately chose a turkey vulture perched on a utility pole. The dark bird against the blue sky provides a clear boundary for testing subject selection.</p>
      <Photos items={[photo('mask-lightcraft.png','LightCraft subject selection','LightCraft red mask includes turkey vulture, pole, and broad surrounding sky',849,726),photo('mask-lightroom.png','Lightroom subject selection','Lightroom red mask follows turkey vulture, pole, and wiring closely',646,649)]} caption="Red shows the selected area. Lightroom leaves most of the surrounding sky outside the mask." />
      <p>LightCraft included a large, softly edged area of sky around the bird and pole. Lightroom followed the vulture, pole, and much of the attached hardware far more precisely.</p><p className="mt-4">Neither mask selected only the bird, but Lightroom gave me a much better starting point. Brightening the subject with the initial LightCraft mask would also brighten surrounding sky. Getting a more isolated adjustment would require manual refinement.</p><p className="mt-4">LightCraft&apos;s masking may be enough for a rough local correction. For precise subject work, this test showed a clear reason to keep Lightroom.</p></section>
      <section id="raw"><h2>Butterfly RAW rendering - A difference before editing</h2><p className="mt-4">The butterfly photo showed another important difference before I applied a preset. LightCraft displayed a broad pink-purple haze in the bright background around the butterfly. Lightroom&apos;s starting preview looked much more neutral.</p>
      <Photos items={[photo('raw-lightroom.png','Lightroom before editing','Lightroom butterfly RAW preview with neutral bright background',574,668),photo('raw-lightcraft.png','LightCraft before editing','LightCraft butterfly RAW preview with broad pink-purple haze',590,652)]} caption="The background difference was visible before the preset and JPEG export." />
      <p>LightCraft also showed more subdued greens in the plant. The haze remained in the exported JPEG, so it was not confined to the editing preview.</p><p className="mt-4">I have not identified the cause. Different profiles, default corrections, or RAW processing could contribute. What I can say is that the two editors gave me visibly different starting points for this file.</p>
      <Photos items={[photo('butterfly-lightroom.jpg','Lightroom JPEG','Preset-applied Lightroom butterfly JPEG with bright background and green thistle',7952,5304),photo('butterfly-lightcraft.jpg','LightCraft JPEG','Preset-applied LightCraft butterfly JPEG showing purple background haze',7952,5304)]} caption="Both preset-applied images were exported at 100% JPEG quality. Web display copies are optimized separately." />
      <p>If you edit backlit subjects, fine edges, or bright backgrounds, try your own RAW files before switching. A familiar interface does not guarantee the same initial rendering.</p></section>
      <section id="exports"><h2>JPEG export sizes - Same pixels, different files</h2><p className="mt-4">Both butterfly exports retained 7,952 × 5,304 pixels, approximately 42.18 megapixels. Despite choosing 100% JPEG quality in both programs, their file sizes differed substantially.</p><div className="overflow-x-auto mt-5"><table className="w-full text-left text-sm"><caption className="sr-only">Original butterfly JPEG export dimensions and file sizes</caption><thead><tr>{['Editor','Dimensions','File size'].map(x=><th key={x} scope="col" className="p-3 border-b border-white/20">{x}</th>)}</tr></thead><tbody><tr><th scope="row" className="p-3 font-normal">Lightroom</th><td className="p-3">7,952 × 5,304</td><td className="p-3">17.71 MB</td></tr><tr><th scope="row" className="p-3 font-normal">LightCraft</th><td className="p-3">7,952 × 5,304</td><td className="p-3">5.07 MB</td></tr></tbody></table></div><p className="mt-4">LightCraft&apos;s original export was about 71% smaller. Lightroom&apos;s was roughly 3.49 times larger. These measurements come from the original exported files, not the optimized images displayed on this page.</p><p className="mt-4">Maximum quality settings are not necessarily equivalent across JPEG encoders. Metadata and image content can also affect size. The smaller file alone does not prove lower quality, and identical dimensions do not prove identical detail.</p></section>
      <section id="workflow"><h2>AI features, cloud storage, and the learning curve</h2><p className="mt-4">I find LightCraft less crowded with AI features, which is both an advantage and a tradeoff. A simpler editing experience appeals to me, but the turkey vulture test shows where better automated tools can save work.</p><p className="mt-4">Adobe&apos;s cloud storage and broader AI-assisted workflow remain advantages for my needs. I did not run a separate cloud-storage comparison or test every AI feature, so those are workflow preferences rather than measured results from these photos.</p><p className="mt-4">Compared with my experience of darktable, LightCraft looks and feels more familiar coming from Lightroom. I still spent time finding controls on the first edit, but the switch did not feel like learning an entirely new editing approach. This is not a full darktable comparison.</p><p className="mt-4">LightCraft is described as free and open source on its <a href="https://getartcraft.com/apps/lightcraft">official product page</a>. That makes trying it with a few representative photos a reasonable way to see whether it fits your workflow.</p></section>
      <section id="verdict"><h2>Can LightCraft replace Lightroom?</h2><p className="mt-4">For straightforward editing, LightCraft is a credible free Lightroom alternative. It works, feels responsive on my computer, and produced results close to Lightroom in several of my examples.</p><p className="mt-4">The tradeoffs are real. The same preset did not produce the same look. Subject detection was much less precise in the vulture test. One RAW file showed a purple haze before editing that persisted through export.</p><p className="mt-4">If your priorities are free editing, familiar controls, and basic adjustments, LightCraft is worth testing. If accurate automatic masks and dependable results from your established presets are central to your work, my comparison gives you reasons to keep Lightroom available.</p><p className="mt-4">My takeaway is that LightCraft is useful, but I would test a representative set of my own photos before treating it as a complete replacement.</p></section>
      <section id="faq"><h2>Frequently asked questions</h2><div className="mt-5 space-y-6">{faqs.map(([q,a]) => <div key={q}><h3>{q}</h3><p className="mt-2">{a}</p></div>)}</div></section>
      <aside className="mt-10 border-t border-white/15 pt-6"><h2>More from my photography workflow</h2><p className="mt-4">Explore <Link href="/photography/camera-bag">the camera gear I use</Link>, read my <Link href="/photography/field-notes/capturing-backyard-birds">backyard bird photography notes</Link>, or browse <Link href="/photography/gallery">my photography gallery</Link>.</p><p className="mt-4 text-sm">All comparison photographs and screenshots are from my own tests. Photo copyright remains with Christopher Brenzel.</p></aside>
    </div>
  </article></main>
}
